import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/appSidebar";
import { Header } from "@/components/header";
import { NotePadProvider } from "@/components/notesPad";
import { AuthProvider } from "@/components/authComponents";
import { getSessionPayloadFromCookie } from "@/lib/session";
import { ClientUser } from "./api/[[...route]]/route";
import { getUserData } from "@/lib/db";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionPayloadFromCookie();
  let profile: ClientUser | null = null;
  if (session) {
    const userProfile = await getUserData(session.uid);
    if (userProfile) {
      profile = {
        email: userProfile.email,
        name: userProfile.name,
        role: userProfile.role,
        isAdmin: userProfile.isAdmin,
      };
    }
  }
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <AuthProvider initProfile={profile}>
          <NotePadProvider>
            <SidebarProvider>
              <div className="flex flex-1">
                <div className="flex-1 flex flex-col h-svh overflow-hidden">
                  <Header />
                  <div className="flex flex-1">
                    <AppSidebar />
                    <div className="relative flex-1">
                      <div className="bg-sidebar size-full"></div>
                      <div className="absolute rounded-tl-2xl inset-0 bg-background">
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </SidebarProvider>
          </NotePadProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
