/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cpt/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Cpt */
        post: operations["generate_cpt_cpt_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/sections/{section_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Section */
        post: operations["run_section_research_sections__section_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/run-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All */
        post: operations["run_all_research_run_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/sections/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Section */
        post: operations["chat_section_research_sections_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Excel */
        get: operations["export_excel_export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Pdf */
        get: operations["export_pdf_export_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApcChatRequest */
        ApcChatRequest: {
            /** Session Id */
            session_id: string;
            /** Cpt */
            cpt: string;
            /** Section Id */
            section_id: string;
            /** Question */
            question: string;
            /**
             * Model
             * @default gpt-5
             */
            model: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "assistant" | "user" | "system";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Model
             * @default gpt-5
             */
            model: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** CptCodeResult */
        CptCodeResult: {
            /**
             * Code
             * @example 31628
             */
            code: string;
            /**
             * Description
             * @example Bronchoscopy, rigid or flexible, including fluoroscopic guidance, when performed; with transbronchial lung biopsy(s), single lobe
             */
            description: string;
            /**
             * Source
             * @example internal_kb
             */
            source: string;
        };
        /** GenerateCptRequest */
        GenerateCptRequest: {
            /** Topic */
            topic: string;
            /**
             * Model
             * @default gpt-4.1-mini
             */
            model: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InternalLlmRecodingResult */
        InternalLlmRecodingResult: {
            /** Cpt Code */
            cpt_code: string;
            /** Description */
            description: string;
            /** Description Source */
            description_source: string;
            llm_recoding: components["schemas"]["LlmRecoding"];
        };
        /** LlmRecoding */
        LlmRecoding: {
            /** Recoding Possibilities */
            recoding_possibilities: string;
            /** Source */
            source: string;
        };
        /** NeighbouringCode */
        NeighbouringCode: {
            /** Cpt Code */
            cpt_code: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** ResearchRunResult */
        ResearchRunResult: {
            /** Target Cpt */
            target_cpt: string;
            /** Context Details */
            context_details: string;
            /** Model */
            model: string;
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["SectionSuccess"] | components["schemas"]["SectionError"];
            };
        };
        /** ResearchSectionRunRequest */
        ResearchSectionRunRequest: {
            /** Cpt */
            cpt: string;
            /**
             * Context
             * @default
             */
            context: string | null;
            /**
             * Model
             * @default gpt-4.1-mini
             */
            model: string;
            /**
             * Use Cache
             * @default true
             */
            use_cache: boolean;
        };
        /** RunAllRequest */
        RunAllRequest: {
            /** Cpt */
            cpt: string;
            /**
             * Context
             * @default
             */
            context: string | null;
            /**
             * Model
             * @default gpt-4.1-mini
             */
            model: string;
            /** Sections To Run */
            sections_to_run?: number[] | null;
            /**
             * Use Cache
             * @default true
             */
            use_cache: boolean;
        };
        /** Section1Data */
        Section1Data: {
            /** Neighbouring Codes */
            neighbouring_codes: components["schemas"]["NeighbouringCode"][];
            /** Internal Recoding Result */
            internal_recoding_result: {
                [key: string]: unknown;
            }[];
            /** Internal Llm Recoding Result */
            internal_llm_recoding_result: components["schemas"]["InternalLlmRecodingResult"][];
            /** External Full Llm Result */
            external_full_llm_result: {
                [key: string]: unknown;
            }[];
        };
        /** SectionError */
        SectionError: {
            /** Section Num */
            section_num: number;
            /**
             * Status
             * @constant
             */
            status: "error";
            /** Error */
            error: string;
        };
        /** SectionSuccess */
        SectionSuccess: {
            /** Section Num */
            section_num: number;
            /**
             * Status
             * @constant
             */
            status: "success";
            /** Data */
            data: components["schemas"]["Section1Data"] | string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Streaming LLM response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cpt_cpt_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CptCodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_section_research_sections__section_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchSectionRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_research_run_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_section_research_sections_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApcChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_export_excel_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pdf_export_pdf_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
