/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cpt/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Cpt */
        post: operations["generate_cpt_cpt_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/run/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Section */
        post: operations["run_section_research_run__section_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/sections/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Section */
        post: operations["chat_section_research_sections_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Excel */
        get: operations["export_excel_export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Pdf */
        get: operations["export_pdf_export_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApcChatRequest */
        ApcChatRequest: {
            /** Session Id */
            session_id: string;
            /** Cpt */
            cpt: string;
            /** Section Id */
            section_id: string;
            /** Question */
            question: string;
            /**
             * Model
             * @default gpt-5
             */
            model: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** CPTDescription */
        CPTDescription: {
            /** Cpt Code */
            cpt_code: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "assistant" | "user" | "system";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Model
             * @default gpt-5
             */
            model: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** CodeDescriptionKbRecoding */
        CodeDescriptionKbRecoding: {
            /** Cpt Code */
            cpt_code: string;
            /** Cpt Description */
            cpt_description: string;
            /** Change Type */
            change_type: string;
            /** Cpt Change Description */
            cpt_change_description: string;
            /** Resource */
            resource: string;
        };
        /** CodeDescriptionNeighbor */
        CodeDescriptionNeighbor: {
            /** Cpt Code */
            cpt_code: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** CodeDescriptionNoChange */
        CodeDescriptionNoChange: {
            /** Cpt Code */
            cpt_code: string;
            /** Description */
            description: string;
            /** Description Source */
            description_source: string;
            /** Status */
            status: string;
        };
        /** CodeDescriptionResult */
        CodeDescriptionResult: {
            /** Neighbouring Codes */
            neighbouring_codes: components["schemas"]["CodeDescriptionNeighbor"][];
            /** Internal Recoding Result */
            internal_recoding_result: components["schemas"]["CodeDescriptionKbRecoding"][];
            /** No Change Results */
            no_change_results: components["schemas"]["CodeDescriptionNoChange"][];
            /** Internal Llm Recoding Result */
            internal_llm_recoding_result?: {
                [key: string]: unknown;
            }[];
            /** External Full Llm Result */
            external_full_llm_result?: {
                [key: string]: unknown;
            }[];
        };
        /** CptCodeResult */
        CptCodeResult: {
            /**
             * Code
             * @example 31628
             */
            code: string;
            /**
             * Description
             * @example Bronchoscopy, rigid or flexible, including fluoroscopic guidance, when performed; with transbronchial lung biopsy(s), single lobe
             */
            description: string;
            /**
             * Source
             * @example internal_kb
             */
            source: string;
        };
        /** DeviceCodeResult */
        DeviceCodeResult: {
            /** Device Codes With Desc */
            device_codes_with_desc: components["schemas"]["DeviceDescription"][];
            /** Internal Recoding Result */
            internal_recoding_result: {
                [key: string]: unknown;
            }[];
            /** No Change Results */
            no_change_results: components["schemas"]["DeviceNoChange"][];
            /** Internal Llm Recoding Result */
            internal_llm_recoding_result?: {
                [key: string]: unknown;
            }[];
            /** External Full Llm Result */
            external_full_llm_result?: {
                [key: string]: unknown;
            }[];
        };
        /** DeviceDescription */
        DeviceDescription: {
            /** Hcpcs Code */
            hcpcs_code: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** DeviceNoChange */
        DeviceNoChange: {
            /** Hcpcs Code */
            hcpcs_code: string;
            /** Description */
            description: string;
            /** Description Source */
            description_source: string;
            /** Status */
            status: string;
        };
        /** ErrorResult */
        ErrorResult: {
            /**
             * Success
             * @default false
             * @constant
             */
            success: false;
            /** Content */
            content?: unknown | null;
            /** Error */
            error: string;
            /** Section Id */
            section_id: string;
            /** Section Title */
            section_title: string;
        };
        /** FinalAssessment */
        FinalAssessment: {
            /** Target Cpt */
            target_cpt: string;
            /** Cpt Descriptions */
            cpt_descriptions: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Ncci Results */
            ncci_results: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Device Codes */
            device_codes: components["schemas"]["DeviceDescription"][];
            /** Payment History */
            payment_history: {
                [key: string]: components["schemas"]["PaymentHistoryEntry"];
            };
            /** Update Time */
            update_time: string;
            /**
             * Source
             * @default internal_kb
             */
            source: string;
        };
        /** GenerateCptRequest */
        GenerateCptRequest: {
            /** Topic */
            topic: string;
            /**
             * Model
             * @default gpt-4.1-mini
             */
            model: string;
        };
        /** GuidelineResult */
        GuidelineResult: {
            /** Analysis Content */
            analysis_content: string;
            /** Cpt Descriptions */
            cpt_descriptions: {
                [key: string]: components["schemas"]["CPTDescription"];
            };
            /**
             * Source
             * @default llm
             */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NcciResult */
        NcciResult: {
            /** Analysis Content */
            analysis_content: string;
            /** Ptp Tables By Cpt */
            ptp_tables_by_cpt: {
                [key: string]: components["schemas"]["PtpTablesForCpt"];
            };
            /** Ncci Manual By Cpt */
            ncci_manual_by_cpt: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Ncci Chunk Details By Cpt */
            ncci_chunk_details_by_cpt: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Neighboring Codes */
            neighboring_codes: string[];
            /** Cpt Descriptions */
            cpt_descriptions: {
                [key: string]: components["schemas"]["CPTDescription"];
            };
            /**
             * Source
             * @default internal_kb
             */
            source: string;
        };
        /** PaymentHistoryEntry */
        PaymentHistoryEntry: {
            /** Data */
            data?: {
                [key: string]: unknown;
            }[];
            /**
             * Has Data
             * @default false
             */
            has_data: boolean;
        };
        /** PaymentRateResult */
        PaymentRateResult: {
            /** Analysis Content */
            analysis_content: string;
            target_cpt_payment_history: components["schemas"]["TargetPaymentHistory"];
            /** Cpt Descriptions */
            cpt_descriptions: {
                [key: string]: components["schemas"]["CPTDescription"];
            };
            /**
             * Source
             * @default llm
             */
            source: string;
        };
        /** PaymentTable */
        PaymentTable: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            /** Data Filtered */
            data_filtered: {
                [key: string]: unknown;
            }[];
            /** Data Filtered Df */
            data_filtered_df?: unknown | null;
            /** Exclusions */
            exclusions: {
                [key: string]: unknown;
            };
            /** Excluded Cpt Codes */
            excluded_cpt_codes: string[];
            /** Record Count */
            record_count: number;
            /** Record Count Filtered */
            record_count_filtered: number;
        };
        /** PtpTable */
        PtpTable: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            /** Record Count */
            record_count: number;
        };
        /** PtpTablesForCpt */
        PtpTablesForCpt: {
            modifier_0?: components["schemas"]["PtpTable"] | null;
            modifier_1?: components["schemas"]["PtpTable"] | null;
            /** Has Data */
            has_data: boolean;
            /** Source */
            source: string;
        };
        /** ReferenceMaterialResult */
        ReferenceMaterialResult: {
            /** Analysis Content */
            analysis_content: string;
            /** Cpt Descriptions */
            cpt_descriptions: {
                [key: string]: components["schemas"]["CPTDescription"];
            };
            /**
             * Source
             * @default llm
             */
            source: string;
        };
        /** RunAllRequest */
        RunAllRequest: {
            /** Cpt */
            cpt: string;
            /**
             * Context
             * @default
             */
            context: string | null;
            /**
             * Model
             * @default gpt-4.1-mini
             */
            model: string;
            /**
             * Use Cache
             * @default true
             */
            use_cache: boolean;
        };
        /** TargetPaymentHistory */
        TargetPaymentHistory: {
            apc: components["schemas"]["PaymentTable"];
            asc: components["schemas"]["PaymentTable"];
            pnpp: components["schemas"]["PaymentTable"];
            /** Source */
            source: string;
            /** Cpt Codes Analyzed */
            cpt_codes_analyzed: string[];
            /** Neighboring Codes */
            neighboring_codes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Streaming LLM response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cpt_cpt_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CptCodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_section_research_run__section_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAllRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeDescriptionResult"] | components["schemas"]["GuidelineResult"] | components["schemas"]["PaymentRateResult"] | components["schemas"]["DeviceCodeResult"] | components["schemas"]["NcciResult"] | components["schemas"]["ReferenceMaterialResult"] | components["schemas"]["FinalAssessment"] | components["schemas"]["ErrorResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_section_research_sections_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApcChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_export_excel_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pdf_export_pdf_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
